import json
import os
from datetime import datetime, timezone
from pathlib import Path

import resend
from dotenv import load_dotenv

load_dotenv()

PROJECT = Path(r"D:\Shoaib Project\Personal-AI-Employee")
VAULT = PROJECT / "AI_Employee_Vault"
LOGS = VAULT / "Logs"
BRIEFINGS = VAULT / "Briefings"
EVIDENCE_SCHEDULING = PROJECT / "evidence" / "gold" / "scheduling"

LOGS.mkdir(parents=True, exist_ok=True)
BRIEFINGS.mkdir(parents=True, exist_ok=True)
EVIDENCE_SCHEDULING.mkdir(parents=True, exist_ok=True)

resend.api_key = os.getenv("RESEND_API_KEY")


def iso_now_utc() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def local_now_display() -> str:
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")


def safe_env(name: str, default: str = "") -> str:
    value = os.getenv(name, default)
    return value.strip() if isinstance(value, str) else default


def write_briefing(ts_utc: str, now_local: str) -> Path:
    filename = f"CEO_BRIEFING_{ts_utc.replace(':', '').replace('-', '')}.md"
    briefing_path = BRIEFINGS / filename

    content = f"""---
generated_at_utc: "{ts_utc}"
report_type: "ceo_briefing"
source: "send_ceo_report.py"
status: "generated"
---

# Personal AI Employee — CEO Briefing

## System Status
- Status: Running
- Report Time: {now_local}
- Project: Personal AI Employee
- Tier: Gold Development

## MCP Servers
- Filesystem MCP: Active
- GitHub MCP: Active
- Slack MCP: Active
- Google Calendar MCP: Active

## Automation Systems
- Email Automation: Working
- Odoo Automation: Active
- Audit Logging: Enabled

## Recent Achievements
- Custom domain email infrastructure configured
- Resend API successfully integrated
- Automated system notification email tested

## Operator Note
This briefing was automatically generated by the Personal AI Employee system.
"""
    briefing_path.write_text(content, encoding="utf-8")
    return briefing_path


def build_email_html(now_local: str, briefing_path: Path) -> str:
    return f"""
<h2>Personal AI Employee - CEO Report</h2>

<h3>System Status</h3>
<ul>
<li>Status: Running</li>
<li>Report Time: {now_local}</li>
<li>Project: Personal AI Employee</li>
<li>Tier: Gold Development</li>
</ul>

<h3>MCP Servers</h3>
<ul>
<li>Filesystem MCP: Active</li>
<li>GitHub MCP: Active</li>
<li>Slack MCP: Active</li>
<li>Google Calendar MCP: Active</li>
</ul>

<h3>Automation Systems</h3>
<ul>
<li>Email Automation: Working</li>
<li>Odoo Automation: Active</li>
<li>Audit Logging: Enabled</li>
</ul>

<h3>Recent Achievements</h3>
<ul>
<li>Custom domain email infrastructure configured</li>
<li>Resend API successfully integrated</li>
<li>Automated system notification email tested</li>
</ul>

<h3>Attached Internal Record</h3>
<ul>
<li>Vault Briefing File: {briefing_path.name}</li>
</ul>

<hr>

<p>This report was automatically generated by the Personal AI Employee system.</p>
"""


def append_log(ts_utc: str, briefing_path: Path, email_result) -> Path:
    log_path = LOGS / "ceo_report_log.jsonl"

    entry = {
        "ts": ts_utc,
        "event": "CEO_REPORT_SENT",
        "briefing_file": briefing_path.name,
        "briefing_path": str(briefing_path),
        "email_to": safe_env("TO_EMAIL"),
        "email_from": safe_env("FROM_EMAIL"),
        "provider": "resend",
        "result": str(email_result),
    }

    with log_path.open("a", encoding="utf-8") as f:
        f.write(json.dumps(entry, ensure_ascii=False) + "\n")

    return log_path


def main() -> None:
    from_email = safe_env("FROM_EMAIL")
    to_email = safe_env("TO_EMAIL")

    if not resend.api_key:
        raise SystemExit("STOP: RESEND_API_KEY is missing in environment.")
    if not from_email:
        raise SystemExit("STOP: FROM_EMAIL is missing in environment.")
    if not to_email:
        raise SystemExit("STOP: TO_EMAIL is missing in environment.")

    ts_utc = iso_now_utc()
    now_local = local_now_display()

    briefing_path = write_briefing(ts_utc, now_local)
    report_html = build_email_html(now_local, briefing_path)

    params = {
        "from": from_email,
        "to": [to_email],
        "subject": "CEO System Report - Personal AI Employee",
        "html": report_html,
    }

    email_result = resend.Emails.send(params)
    log_path = append_log(ts_utc, briefing_path, email_result)

    print(f"[OK] generated briefing: {briefing_path}")
    print(f"[OK] email result: {email_result}")
    print(f"[OK] log updated: {log_path}")


if __name__ == "__main__":
    main()