import os
import resend
from dotenv import load_dotenv
from datetime import datetime

load_dotenv()

resend.api_key = os.getenv("RESEND_API_KEY")

now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

params = {
    "from": os.getenv("FROM_EMAIL"),
    "to": [os.getenv("TO_EMAIL")],
    "subject": "Personal AI Employee – System Status Report",
    "html": f"""
    <h2>Personal AI Employee System Report</h2>

    <h3>System Status</h3>
    <ul>
        <li><strong>Status:</strong> Running</li>
        <li><strong>Report Time:</strong> {now}</li>
        <li><strong>Domain:</strong> ai.shoaib.ink</li>
    </ul>

    <h3>MCP Infrastructure</h3>
    <ul>
        <li>Filesystem MCP: Active</li>
        <li>GitHub MCP: Active</li>
        <li>Slack MCP: Active</li>
        <li>Google Calendar MCP: Active</li>
    </ul>

    <h3>Automation Services</h3>
    <ul>
        <li>Email System: Operational</li>
        <li>Odoo Automation: Running</li>
        <li>Audit Logs: Recording</li>
    </ul>

    <h3>Recent Actions</h3>
    <ul>
        <li>Email infrastructure verified</li>
        <li>Resend API integration successful</li>
        <li>Automation pipeline tested</li>
    </ul>

    <hr>

    <p>This message was automatically generated by your Personal AI Employee system.</p>
    <p>Project Status: Gold Tier Development</p>
    """,
}

email = resend.Emails.send(params)

print(email)